import {AppImages} from '../../assets';
import {SCREEN} from '../../constants';
import {useHome} from '../../screens/App/home/hooks';

export const PlanData = [
  {
    id: '1',
    title: `Ad-Free Subscription\n($4.99/month)`,
    description:
      'Upgrade to our monthly subscription for an uninterrupted, ad-free experience.',
    showTag: 'Ok',
  },
  {
    id: '2',
    title: 'Free with Ads',
    description:
      'Enjoy the full app experience at no cost, with occasional in-app advertisements',
  },
];

export const GamesData = [
  {
    id: '1',
    image: AppImages.Game1,
    name: 'Sudoku Word Trivia ',
    score: '3/150',
    volume: 'Volume 1',
    star: 'All Star Nines',
    description:
      'Crazy For Sudoku Word Trivia All Star Nines (150 Puzzles) Digital Copy',
    onPress: SCREEN.sudukuGame,
  },
  {
    id: '2',
    image: AppImages.Game2,
    name: 'Color Block Sudoku',
    volume: 'BOOK 1',
    onPress: SCREEN.colorBlockGame,
  },
];

export const ColorBoxData = [
  {
    id: '1',
    color: '#41A5CF',
  },
  {
    id: '2',
    color: '#FFD53F',
  },
  {
    id: '3',
    color: '#FF204D',
  },
  {
    id: '4',
    color: '#5FA35D',
  },
  {
    id: '5',
    color: '#FFFF4B',
  },
  {
    id: '6',
    color: '#FF8300',
  },
  {
    id: '7',
    color: '#FF1780',
  },
  {
    id: '8',
    color: '#00CC00',
  },
  {
    id: '9',
    color: '#A200A2',
  },
];

export const ProfileCardData = [
  {
    id: '1',
    title: 'Word Trivia Average Time Per Game',
    score: '04:85',
    percent: '+23.47%',
  },
  {
    id: '2',
    title: 'Word Trivia Hints Used per Game',
    score: '300',
    percent: '-23.47%',
    arrowDown: 'Ok',
  },
  {
    id: '3',
    title: 'Color Trivia Average Time Per Game',
    score: '03:85',
    percent: '+13.47%',
  },
  {
    id: '4',
    title: 'Color Trivia Hints Used per Game',
    score: '110',
    percent: '+23.47%',
  },
];

export const InstructionBtnsData = [
  {
    id: '1',
    volume: 'VOLUME 1',
    description: `The object of Sudoku Word Trivia is to fill in each empty box with one of nine letters. Each letter can only appear once in each row, column, and block of nine.\n\nEach finished puzzle will contain the answer word or words to the trivia clue. Answer the trivia clue and place it in the proper row or column to help you solve the puzzle. Answers will be from 5-9 letters long. Answers with less than 9 letters will have filler letters to make up the difference. If you get stuck on the clue or you are not sure where it should go in the puzzle, try to fill in some letters to help you.You don’t have to know the answer to solve the puzzle, but if you can guess what the answer is and where it goes in the puzzle it will give you some extra starter letters giving you an easier skill level.\n\nIf you need help getting started click the hint button for free letter hints.\n\nI hope you enjoy my Sudoku Word Trivia Book Volume One. If you have any questions or comments, you can visit my website at `,
  },
  {
    id: '2',
    volume: 'VOLUME 2',
    description: `The object of Sudoku Word Trivia is to fill in each empty box with one of nine letters. Each letter can only appear once in each row, column, and block of nine.\n\nEach finished puzzle will contain the answer word or words to the trivia clue. Answer the trivia clue and place it in the proper row or column to help you solve the puzzle. Answers will be from 5-9 letters long. Answers with less than 9 letters will have filler letters to make up the difference. If you get stuck on the clue or you are not sure where it should go in the puzzle, try to fill in some letters to help you.You don’t have to know the answer to solve the puzzle, but if you can guess what the answer is and where it goes in the puzzle it will give you some extra starter letters giving you an easier skill level.\n\nIf you need help getting started click the hint button for a free letter hint.\n\nI hope you enjoy my Sudoku Word Trivia Book Volume Two. If you have any questions or comments, you can visit my website at`,
  },
  {
    id: '3',
    volume: 'VOLUME 3',
    description: `The object of Sudoku Word Trivia is to fill in each empty box with one of nine letters. Each letter can only appear once in each row, column, and block of nine.\n\nEach finished puzzle will contain the answer word or words to the trivia clue. Answer the trivia clue and place it in the proper row or column to help you solve the puzzle. Answers will be from 5-9 letters long. Answers with less than 9 letters will have filler letters to make up the difference. If you get stuck on the clue or you are not sure where it should go in the puzzle, try to fill in some letters to help you.You don’t have to know the answer to solve the puzzle, but if you can guess what the answer is and where it goes in the puzzle it will give you some extra starter letters giving you an easier skill level.\n\nIf you need help getting started click the hint button for a free letter hint.\n\nI hope you enjoy my Sudoku Word Trivia Book Volume Three. If you have any questions or comments, you can visit my website at `,
  },
  {
    id: '4',
    volume: 'VOLUME 4',
    description: `The object of Sudoku Word Trivia is to fill in each empty box with one of nine letters. Each letter can only appear once in each row, column, and block of nine.\n\nEach finished puzzle will contain the answer word or words to the trivia clue. Answer the trivia clue and place it in the proper row or column to help you solve the puzzle. Answers will be from 5-9 letters long. Answers with less than 9 letters will have filler letters to make up the difference. If you get stuck on the clue or you are not sure where it should go in the puzzle, try to fill in some letters to help you.You don’t have to know the answer to solve the puzzle, but if you can guess what the answer is and where it goes in the puzzle it will give you some extra starter letters giving you an easier skill level.\n\nIf you need help getting started click the hint button for a free letter hint.\n\nI hope you enjoy my Sudoku Word Trivia Book Volume Four. If you have any questions or comments, you can visit my website at`,
  },
  {
    id: '5',
    volume: 'VOLUME 5',
    description: `The object of Sudoku Word Trivia is to fill in each empty box with one of nine letters. Each letter can only appear once in each row, column, and block of nine.\n\nEach finished puzzle will contain the answer word to the trivia clue. Answer the trivia clue and place it in the proper row or column to help you solve the puzzle. In this Specialty Volume, Fabulous Fives, trivia answers will use 5 letters. There will be 4 random filler letters to make up the difference. If you get stuck on the clue or you’re not sure where it should go in the puzzle, try to fill in some letters to help you. You don’t have to know the answer to solve the puzzle, but if you can guess what the answer is and where it goes in the puzzle it will give you some extra starter letters giving you an easier skill level.\n\nIf you need help getting started click the hint button for a free letter hint\n\nI hope you enjoy the 5th volume in my Sudoku Word Trivia Series: Fabulous Fives. If you have any questions or comments, you can visit my website at `,
  },
  {
    id: '6',
    volume: 'VOLUME 6',
    description: `The object of Sudoku Word Trivia is to fill in each empty box with one of nine letters.Each letter can only appear once in each row, column, and block of nine.\n\nEach finished puzzle will contain the answer word to the trivia clue. Answer the trivia clue and place it in the proper row or column to help you solve the puzzle. In this Specialty Volume, Super Sixes, trivia answers will use 6 letters. There will be 3 random filler letters to make up the difference. If you get stuck on the clue or you’re not sure where it should go in the puzzle, try to fill in some letters to help you. You don’t have to know the answer to solve the puzzle, but if you can guess what the answer is and where it goes in the puzzle it will give you some extra starter letters giving you an easier skill level.\n\nIf you need help getting started click the hint button for a free letter hint.\n\nI hope you enjoy the 6th volume in my Sudoku Word Trivia Series: Super Sixes. If you have any questions or comments, you can visit my website at`,
  },
  {
    id: '7',
    volume: 'VOLUME 7',
    description: `The object of Sudoku Word Trivia is to fill in each empty box with one of nine letters. Each letter can only appear once in each row, column, and block of nine.\n\nEach finished puzzle will contain the answer word to the trivia clue. Answer the trivia clue and place it in the proper row or column to help you solve the puzzle. In this Specialty Volume, Pleasant Sevens, trivia answers will use 7 letters. There will be 2 random filler letters to make up the difference. If you get stuck on the clue or you’re not sure where it should go in the puzzle, try to fill in some letters to help you. You don’t have to know the answer to solve the puzzle, but if you can guess what the answer is and where it goes in the puzzle it will give you some extra starter letters giving you an easier skill level.\n\nIf you need help getting started click the hint button for a free letter hint.\n\nI hope you enjoy the 7th volume in my Sudoku Word Trivia Series: Pleasant Sevens. If you have any questions or comments, you can visit my website at`,
  },
  {
    id: '8',
    volume: 'VOLUME 8',
    description: `The object of Sudoku Word Trivia is to fill in each empty box with one of nine letters. Each letter can only appear once in each row, column, and block of nine.\n\nEach finished puzzle will contain the answer word to the trivia clue. Answer the trivia clue and place it in the proper row or column to help you solve the puzzle. In this Specialty Volume, Crazy Eights, trivia answers will use 8 letters. There will be 1 random filler letter to make up the difference. If you get stuck on the clue or you’re not sure where it should go in the puzzle, try to fill in some letters to help you. You don’t have to know the answer to solve the puzzle, but if you can guess what the answer is and where it goes in the puzzle it will give you some extra starter letters giving you an easier skill level.\n\nIf you need help getting started click the hint button for a free letter hint.\n\nI hope you enjoy the 8th volume in my Sudoku Word Trivia Series: Crazy Eights. If you have any questions or comments, you can visit my website at `,
  },
  {
    id: '9',
    volume: 'VOLUME 9',
    description: `The object of Sudoku Word Trivia is to fill in each empty box with one of nine letters. Each letter can only appear once in each row, column, and block of nine.\n\nEach finished puzzle will contain the answer word(s) to the trivia clue. Answer the trivia clue and place it in the proper row or column to help you solve the puzzle. In this Specialty Volume, All Star Nines, all 150, 9 letter trivia answers and their clues from Volumes 1-4 have returned. They’ve changed positions in the line-up and in the grids. Test your memory! Do you remember any of these All-Star Nines. If you get stuck on the clue or you’re not sure where it should go in the puzzle, try to fill in some letters to help you. You don’t have to know the answer to solve the puzzle, but if you can guess what the answer is and where it goes in the puzzle it will give you some extra starter letters giving you an easier skill level.\n\nIf you need help getting started click the hint button for a free letter hint.\n\nI hope you enjoy the 9th volume in my Sudoku Word Trivia Series: All-Star Nines. If you have any questions or comments, you can visit my website at `,
  },
];

export const InitalSudokuGameData = [
  'S',
  null,
  null,
  'I',
  null,
  null,
  'O',
  'T',
  null,
  'O',
  'B',
  null,
  'N',
  'D',
  null,
  null,
  'S',
  'M',
  null,
  null,
  'C',
  'M',
  null,
  null,
  null,
  'B',
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  'M',
  null,
  null,
  'M',
  null,
  'O',
  'B',
  'T',
  'N',
  'I',
  'D',
  null,
  'D',
  'I',
  null,
  null,
  'C',
  null,
  null,
  'O',
  null,
  null,
  'N',
  null,
  null,
  null,
  null,
  'B',
  null,
  null,
  null,
  null,
  'S',
  'D',
  'M',
  null,
  null,
  'N',
  'C',
  'T',
  null,
  'B',
  null,
  'N',
  'I',
  'S',
  null,
  null,
];

const color1 = '#41A5CF';
const color2 = '#FFD53F';
const color3 = '#FF204D';
const color4 = '#5FA35D';
const color5 = '#FFFF4B';
const color6 = '#FF8300';
const color7 = '#FF1780';
const color8 = '#00CC00';
const color9 = '#A200A2';

export const InitialColorBlockGameData = [
  null,
  color5,
  null,
  null,
  null,
  color1,
  null,
  color2,
  color4,
  null,
  null,
  color4,
  color5,
  color3,
  null,
  color8,
  null,
  null,
  color6,
  null,
  null,
  null,
  color7,
  null,
  color1,
  null,
  null,
  null,
  null,
  color7,
  null,
  null,
  null,
  null,
  null,
  color2,
  null,
  color9,
  null,
  color4,
  null,
  color7,
  null,
  null,
  null,
  null,
  color1,
  null,
  color3,
  null,
  null,
  color4,
  color9,
  null,
  color4,
  null,
  null,
  null,
  color6,
  color5,
  null,
  null,
  null,
  color7,
  color8,
  null,
  null,
  color1,
  null,
  color6,
  null,
  color3,
  null,
  null,
  color1,
  null,
  null,
  null,
  color9,
  null,
  null,
];
